# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

myCluster <- function(n, D_, method = 0L) {
    .Call(`_myCluster_myCluster`, n, D_, method)
}

